### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by iannellog** [agnesebonfigli99/Tombola#1]
Da quello che vedo Agnese è l'unica che può effettuare push (non ci sono altri contributors). L'idea invece è che siate tutti e quattro contributors e possiate fare push (naturalmente coordinandovi per evitare conflitti).
Tra l'altro vedo che avete aperto due branch di test per cui avete già prefigurato la possibilità che lavorate in due sotto gruppi, almeno in una fase iniziale.
Quindi Agnese dovrebbe aggiungere gli altri tre come contributors.

**Comment by agnesebonfigli99** [comment]
Buongiorno professore, 
La ringrazio per l’appunto. 
Provvederemo a includere tutti come Contributors. 

Grazie, 
Cordiali saluti, 
Bonfigli Agnese.



Inviato da myMail per iOS


venerdì 29 aprile 2022, 00:17 -0700 da ***@***.***  ***@***.***>:

**Comment by iannellog** [comment]
Come ho scritto nella mail a Francesco, non risultate ancora tutti contributors.
Provvedete così tutti ricevono le notifiche. 
Dovete tutti conoscere la storia del progetto ed essere in grado di interagire nella discussione se volete una buona valutazione individuale.
